### PR TITLE
Noisy script output

### LINKED ISSUE #97: bootstrap script output is too noisy
We should eliminate set -x from all the scripts

### PR DESCRIPTION
**Pull request by Bill-Keuntje**
Fix #97 (noisy script output)
Additional changes for #69, #63, #64

### CODE REVIEW

**Review by jimscarver — CHANGES_REQUESTED** [review]
conflicts need resolution.

**Comment by Bill-Keuntje** [comment]
I believe Tom's previously approved pull request covers the changes in this pull request.
If @w2vy will confirm, then this pull request can be cancelled/removed/closed/thrown-in-the-pit-of-despair.

**Comment by Bill-Keuntje** [comment]
@w2vy please confirm the previous comment?

**Comment by Bill-Keuntje** [comment]
Cancelled

**Pull request closed without merging**
