### PR TITLE
move dckc out of leadership role

### PR DESCRIPTION
**Pull request by dckc**
I'm no longer sufficiently available

### CODE REVIEW

**Comment by jimscarver** [comment]
your contribution has been substantial. I prefer to keep your recognition in even though your participation may be slight. We still are completing your ideas including the trust metric.

**Review by Bill-Kunj — COMMENTED** [review]
I agree with @jimscarver (https://github.com/rchain-community/rgov/pull/272#issuecomment-917018272) that this is inappropriate. @dckc attribution belongs in RGOV.

**Comment by Bill-Kunj** [comment]
@dckc Please close this PR

**Comment by dckc** [comment]
ok, we'll see how it goes and whether I want to revisit this.

**Pull request closed without merging**
