### PR TITLE
Fix newinbox

### LINKED ISSUE #181: master needs to be tested - newInbox seems to fail
Log shows 

{"master-dictionary dictionary unforgeable" : Nil}

@Bill-Keuntje @jimscarver

### PR DESCRIPTION
**Pull request by Bill-Keuntje**
Fixes #181 

Handle MasterURI when loading actions in participate (javascript)
Add logging when inserting MemberDirectory into MasterDirectory (rholang)
fix bootstrap output messages when fetching master dictionary (rholang)
update typescript to include "MasterURI" field type. (typescript)

### CODE REVIEW

**Comment by Bill-Keuntje** [comment]
Tested with a new bootstrap/deploy-all.

This code will NOT work with a pre-existing rnode database.

**Comment by jimscarver** [comment]
now I get
```
{"master-dictionary dictionary unforgeable" : bundle+ {   Unforgeable(0x6cffb7cf5263cf2747fe068a7ffd16810d6fd2cb20a51cc0a2230213c4976b0c) }}
{"master-dictionary GetMe unforgeable" : Nil}
```
fix
```
git checkout fix-newinbox
 ./restore-snapshot rgov
 ./run-rnode
  ./deploy ../MemberDirectory.rho
 ./deploy listMasterURI.rho
./propose
#test to see if it worked
 ./create-snapshot rgov
```
localhost works now but i did not get it to work on rhobot

**Comment by Bill-Keuntje** [comment]
> now I get
> 
> ```
> {"master-dictionary dictionary unforgeable" : bundle+ {   Unforgeable(0x6cffb7cf5263cf2747fe068a7ffd16810d6fd2cb20a51cc0a2230213c4976b0c) }}
> {"master-dictionary GetMe unforgeable" : Nil}
> ```
> 
> fix
> 
> ```
> git checkout fix-newinbox
>  ./restore-snapshot rgov
>  ./run-rnode
>   ./deploy ../MemberDirectory.rho
>  ./deploy listMasterURI.rho
> ./propose
> #test to see if it worked
>  ./create-snapshot rgov
> ```
> 
> localhost works now but i did not get it to work on rhobot

Fixed by latest commit/push to fix-newinbox branch.

**Review by jimscarver — APPROVED** [review]
this is not a complete fix, but is closer and have a process to make it right verified by 3 of us so I will merge it

**Comment by jimscarver** [comment]
again i am getting {"master-dictionary dictionary unforgeable" : Nil}

**Review by dckc — COMMENTED** [review]
changes to actions.js and participate.js look good.

**Comment by w2vy** [comment]
Tested on master and looks good to me

On June 2, 2021 5:32:15 PM EDT, Jim Whitescarver ***@***.***> wrote:
>Merged #182 into master.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/rchain-community/rgov/pull/182#event-4834200945

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dckc** [comment]
> changes to actions.js and participate.js look good.

oops; I assumed they passed `lint-check` and `lint-types`. We still don't have robots checking those, do we? Sigh.

**Pull request merged**
