### PR TITLE
fix bogus code in rholang pane when deployed to dist dir

### PR DESCRIPTION
**Pull request by jimscarver**
test rgov1.netlify.app when merged.

### CODE REVIEW

**Comment by jimscarver** [comment]
Do you know why we have npm build issues @dckc ?

**Comment by jimscarver** [comment]
merge in 54-build-cp to fix problem

**Comment by dckc** [comment]
> Do you know why we have npm build issues @dckc ?

#84 has no build issues.

Why was this merged without review? It conflicts with #84 .

Why use a spacer filename rather than no filename?

**Comment by jimscarver** [comment]
Bill and I reviewed the simple change together yesterday and the netlify deploys were still showing javascript code. No filename may be better, a file was an easy solution for bill. . Remember to are javascript neophytes getting anything to work can be a challenge. Something that works simply can be improved later.

**Comment by dckc** [comment]
@Bill-Keuntje when you review a PR, please tell github.

**Pull request merged**
