### PR TITLE
feat: store #define bindings in localStorage; clock UI

### PR DESCRIPTION
**Pull request by dckc**
persistence is handy for the console (#39) and blockly (#40) UI ideas.

### CODE REVIEW

**Comment by Bill-Keuntje** [comment]
@dckc Would like to discuss this in person to get a better understanding.

**Comment by dckc** [comment]
> @dckc Would like to discuss this in person to get a better understanding.

Suggest a time or two?

**Comment by Bill-Keuntje** [comment]
Your schedule is more restricted than mine. Let me know.

**Comment by dckc** [comment]
I'm in no rush.

**Review by jimscarver — APPROVED** [review]
i don't really understand this fully but it seems benign.

**Comment by Bill-Keuntje** [comment]
Everyone seems to agree this is OK, but there are conflicts. Does anyone know what's going on with this?

**Comment by dckc** [comment]
What's going on is that other stuff got added while this was in review, so now this needs someone to resolve the merge conflicts.

I can probably figure out how, but I don't know when.

**Comment by Bill-Keuntje** [comment]
The merge conflicts only get worse with time, and it seems we're gonna need this functionality sometime soon....

**Review by jimscarver — APPROVED** [review]
I did not test but it looks okay.

**Review by jimscarver — COMMENTED** [review]
oops, The conflict is worse than I thought.

**Comment by Bill-Keuntje** [comment]
Refactoring participate (#143) for the UI will conflict with this as well.

**Comment by dckc** [comment]
Perhaps I'll get back to this, but I think it's better to signal that it's unlikely, for now.

**Pull request closed without merging**
