### PR TITLE
refactor participate.js // initial UX implementation (issue #116)

### PR DESCRIPTION
**Pull request by Bill-Keuntje**
Issue #116

### CODE REVIEW

**Comment by Bill-Keuntje** [comment]
There's a lot of merge-type changes included in this. It needs a rebase/merge with the newest master.

**Review by jimscarver — COMMENTED** [review]
you should pull and merge master first.

**Review by jimscarver — CHANGES_REQUESTED** [review]
why change Group.rho??? It will surely conflict with the latest version in group support?

Pleas merge group support first as well as master.

**Review by dckc — CHANGES_REQUESTED** [review]
gak! a 4MB bootstrap.tgz ? Why would we check that in?

**Comment by Bill-Keuntje** [comment]
@w2vy @dckc 
So, this pull request has gone all wrong.
How do I close this one and create another that is more proper?

**Comment by dckc** [comment]
Not sure I understand the question. There's a button to close a PR. Then make a new one.

If the old one (this one) has some good commits, you can cherry pick them.

**Pull request closed without merging**
