### PR TITLE
fix: dropdown-spacer filename, ToDo list, ambient access to document; clean up lint-check, lint:types

### LINKED ISSUE #60: document ocap discipline for contributors
a la https://github.com/rchain-community/rchain-api/blob/master/CONTRIBUTING.md#object-capability-ocap-discipline

cc @jimscarver @Bill-Keuntje

### LINKED ISSUE #80: ambient access to document in buildUI
https://github.com/rchain-community/liquid-democracy/blob/ee833a26c0279704a1fff88e84b8be3fa91db2f0/src/participate.js#L300

### PR DESCRIPTION
**Pull request by dckc**
fixes #80 
refs #12 - almost fixes it, but #12 should stay open until we have github actions enforcing `lint-check` and `lint:types`.
refs #87
fixes #60

The diffs are organized to facilitate review; I recommend reading them individually rather than looking at the whole PR at once.

### CODE REVIEW

**Review by jimscarver — CHANGES_REQUESTED** [review]
Setting network based on hostname is broken. running on localhost the network default to mainnet
image

**Review by Bill-Keuntje — APPROVED** [review]
I agree with all of this

**Comment by dckc** [comment]
Good catch, @jimscarver . I think I fixed the network selection in  db99c4e ; please take another look.

**Comment by jimscarver** [comment]
localhost still defaults to mainnet @dckc

**Comment by dckc** [comment]
Odd. I tested localhost. It works for me. I wonder what we're doing differently.

**Comment by jimscarver** [comment]
i suppose i don't know how to test it. When I check out and pull I get```
Merge branch 'style-ocap-lint-tsc' of https://github.com/rchain-community/liquid-democracy into style-ocap-lint-tsc
```
with 3 merge conflicts. If I accept the incoming the interface is broke
---
this seems to fix it
```
git fetch --all
git reset --hard origin/style-ocap-lint-tsc
```
and the interface default works....

**Review by jimscarver — APPROVED** [review]

**Review by jimscarver — CHANGES_REQUESTED** [review]
exploy and deploy fail
image

**Comment by dckc** [comment]
explore and deploy work fine for me.

A screenshot doesn't give me enough information to reproduce the problem. Please tell me the exact steps you used.

**Comment by dckc** [comment]
> explore and deploy fail

does df80833 fix it, @jimscarver ?

**Review by jimscarver — APPROVED** [review]

**Pull request merged**
