### PR TITLE
Reviewers please test: fix rholang location

### PR DESCRIPTION
**Pull request by Bill-Kunj**
Fixes 252: Tested and working on localhost

### CODE REVIEW

**Comment by w2vy** [comment]
I was able to run bootstrap/deploy-all and all unit tests

**Comment by w2vy** [comment]
@Bill-Kunj Should I approve this and merge or do you want to wait for @jimscarver to review also?

**Review by jimscarver — APPROVED** [review]
looks ok to me. if you prefer you can wait for my test or I can test after the pull

**Comment by jimscarver** [comment]
this does not look good:
```
fatal: destination path 'rchain' already exists and is not an empty directory.
```
did a make install and start, working great.

**Comment by Bill-Kunj** [comment]
> this does not look good:
> 
> ```
> fatal: destination path 'rchain' already exists and is not an empty directory.
> ```
> 
> did a make install and start, working great.

This message is covered under #253.

**Pull request merged**
